### ISSUE TITLE
Referencesの一番上の項目のリンク先が間違っている

### ISSUE THREAD

**Issue by aMasamichiAndo** [skirino/presentation_on_CAP_theorem#1]
http://webpages.cs.luc.edu/~pld/353/gilbertlynchbrewer_proof.pdf
に対するリンクが正しくない。

````
- [http://webpages.cs.luc.edu/~pld/353/gilbert_lynch_brewer_proof.pdf]()
- http://www.cs.berkeley.edu/~rxin/db-papers/CAP.pdf
- http://codahale.com/you-cant-sacrifice-partition-tolerance/
...
````
という記載になっており、一番上だけ空リンクになっている。

**Comment by skirino** [comment]
ご指摘ありがとうございます!
https://github.com/skirino/presentation_on_CAP_theorem/commit/39ebbb095594eccc24fb20271d5130379e7d94d3
https://github.com/skirino/presentation_on_CAP_theorem/commit/814227b61f542690532089a0496bb5553bde2031
で修正しました。
